Select * from INFORMATION_SCHEMA.TABLES
Select * from INFORMATION_SCHEMA.COLUMNS
--Dimension exploration
--Explore all countries our customers come from
Select distinct  country from gold.dim_customers;
--Explore all categories the major divisions
Select distinct category, subcategory, product_name from gold.dim_products;
-- Find the date of the first and last order 
Select MIN(order_date) as FirstOrderDate, MAX(order_date) LastOrderDate,
--How many orders years of sales are available
DATEDIFF(month, Min(order_date), MAX(order_date)) as order_range_years
from gold.fact_sales;
--Find the youngest and the oldest customer
select min(birthdate) as Oldest_Birthdate,DATEDIFF(year, min(birthdate), GETDATE()) as oldest_age, MAX(birthdate) AS Youngest_Bithdate, DATEDIFF(year, MAX(birthdate), GETDATE()) as youngest_age from gold.dim_customers;
--Measures exploration
--Find the total sales amount
select sum(sales_amount) as Total_Sales from gold.fact_sales;
--Find how many items are sold in total
select sum(quantity) as Total_Quantity from gold.fact_sales;
--Find the average selling price
select avg(price) as Average_Price from gold.fact_sales;
--Find the Total number of Orders
select count(order_number) as avg_price from gold.fact_sales;
select count(DISTINCT order_number) as avg_price from gold.fact_sales;
--Find the total number of products 
Select count(product_key) as total_products from gold.dim_products;
Select count(DISTINCT product_key) as total_products from gold.dim_products;
--Find the total number of customers
Select count(customer_key) as total_customers from gold.dim_customers;
--Find the total number of customers that has placed an order
select count (customer_key) as total_customers from gold.fact_sales;
select count (DISTINCT customer_key) as total_customers from gold.fact_sales;
--Generate a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(sales_amount) as measures_value from gold.fact_sales
union all
select 'Total Quantity', sum(quantity) from gold.fact_sales
union all
select 'Average Price', avg(price) from gold.fact_sales
union all
select 'Total NR. Orders', count(DISTINCT order_number) from gold.fact_sales
union all
select 'Total NR. Products', count(DISTINCT product_name) from gold.dim_products
union all
select 'Total NR. Customers', count(customer_key) from gold.dim_customers;
--Measures exploration 
--Find total customers by countries
select country, count(customer_key) as total_customers from gold.dim_customers group by country order by total_customers desc;
--Find total customers by gender
select gender, count(customer_key) as total_customers from gold.dim_customers group by gender order by total_customers desc;
--Find total products by category
select category, count(product_key) as total_products from gold.dim_products group by category order by total_products desc;
--what is the average costs in each category?
select category, avg(cost) as average_costs from gold.dim_products group by category order by average_costs desc;
--what is the total revenue generated for each category?
select p.category, sum(f.sales_amount) total_revenue from gold.fact_sales f left join gold.dim_products p on p.product_key = f.product_key group by p.category order by total_revenue desc;
--what is the total revenue generated by each customer?
select c.customer_key, c.first_name, c.last_name, sum(f.sales_amount) as total_revenue from gold.fact_sales f left join gold.dim_customers c on c.customer_key = f.customer_key group by c.customer_key, c.first_name, c.last_name order by total_revenue desc;
--what is the distribution of sold items across countries?
select c.country, sum(f.quantity) as total_sold_items from gold.fact_sales f left join gold.dim_customers c on c.customer_key=f.customer_key group by c.country order by total_sold_items desc;
--Ranking
--Which 5 products genearte the highest revenue?
select TOP 5 p.subcategory, sum(f.sales_amount) as total_revenue from gold.fact_sales f left join gold.dim_products p on p.product_key = f.product_key group by p.subcategory order by total_revenue desc;
--What are the 5 worst-performing products in terms of sales?
select * from (select p.product_name, sum(f.sales_amount) as total_revenue, ROW_NUMBER() over (order by sum(f.sales_amount) desc) as rank_products from gold.fact_sales f left join gold.dim_products p on p.product_key = f.product_key group by p.product_name)t where rank_products<=5;
--Find the top 10 customers who have generated the highest revenue
select top 10 c.customer_key, c.first_name, c.last_name, sum(f.sales_amount) as total_revenue from gold.fact_sales f left join gold.dim_customers c on c.customer_key = f.customer_key group by c.customer_key, c.first_name, c.last_name order by total_revenue;
--The 3 customers with the fewest orders placed
select top 3 c.customer_key, c.first_name, c.last_name, count(DISTINCT  order_number) as total_orders from gold.fact_sales f left join gold.dim_customers c on c.customer_key = f.customer_key group by c.customer_key, c.first_name, c.last_name order by total_orders;